import React, { useEffect } from "react";
import {
	getWebAuthnCredentials,
	isWebAuthnSupported,
	registerWebAuthn,
} from "./helpers/web-authn";

const App = () => {
	useEffect(() => {
		if (!isWebAuthnSupported()) return;

		registerWebAuthn().then((credential) => {
			if (!credential) return;

			console.log(credential);
      
			getWebAuthnCredentials(credential as PublicKeyCredential).then(
				(assertion) => {
					// Use the assertion.response.signature value to verify using the public key stored on the server.
					// If the signature generated by the private key stored in the browser, can be decrypted using the public key stored on the server.
					// Then the user can be safely assumed to be valid and logged in.
					console.log(assertion);
				}
			);
		});
	}, []);

	return <div className="App"></div>;
};

export default App;
